theme = "slick"
icons = "none"

# [[block]]
# block = "temperature"
# collapsed = false
# interval = 10
# format = "{max}° max, {average}° avg"

# [[block]]
# block = "focused_window"
# max_width = 21

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{5m}"

[[block]]
block = "networkmanager"
on_click = "/usr/bin/networkmanager_dmenu"
max_ssid_width = 8
ap_format = "{ssid} {strength}"
device_format = "{ap}"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
device = "cw2015-battery"

[[block]]
block = "time"
interval = 60
format = "%m/%d %a %R"
