#!/bin/sh
lock() {
	scrot /tmp/screen_locked.png
	convert /tmp/screen_locked.png -blur 15x4 /tmp/screen_locked2.png
	rm /tmp/screen_locked.png
	i3lock -i /tmp/screen_locked2.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        pkill gnome-session
        ;;
    suspend)
        lock && pmi action suspend
        ;;
    hibernate)
        lock && pmi action hibernate
        ;;
    reboot)
        dbus-send --system --dest=org.freedesktop.Hal --type=method_call --print-reply /org/freedesktop/Hal/devices/computer org.freedesktop.Hal.Device.SystemPowerManagement.Reboot int32:0
        ;;
    shutdown)
        dbus-send --system --dest=org.freedesktop.Hal --type=method_call --print-reply /org/freedesktop/Hal/devices/computer org.freedesktop.Hal.Device.SystemPowerManagement.Shutdown int32:0
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
